### ISSUE TITLE
SUPPORT: Parameter dynamic injection

### ISSUE THREAD

**Issue by wanglei4687** [matrixorigin/matrixone-operator#10]
# Overview
operator shoud inject parameters when pod start time. It is about raft sync and broad cast (advertise addr and listen addr)

# tasks
- [ ] Optimize config generate method
- [ ] Matrixone Cube configuration Intergration, link  [matrixcube PR #547](https://github.com/matrixorigin/matrixcube/pull/574)
- [ ] Matrixone Operator configuration dynamic injection Scripts
- [ ] Operator Intergration

**Comment by wanglei4687** [comment]
Through the Entrypoint script of Docker
