### ISSUE TITLE
[Feature Request]: Umbrella issue of implementing LogSet controller

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone-operator#136]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Implement LogSet controller according to https://github.com/matrixorigin/matrixone-operator/blob/main/docs/rfc/2022-07-04-logset.md

Tasks:
- [x] LogSet API
- [x] HAKeeper bootstrap
- [x] LogStore failover https://github.com/matrixorigin/matrixone-operator/issues/151
- [x] Object Storage Integration

close https://github.com/matrixorigin/matrixone/issues/3540
close https://github.com/matrixorigin/matrixone/issues/3541

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
LogSet should have detailed documentations on the CR definition, which guides users how to use the API.
```

**Comment by aylei** [comment]
> Can we support both local SSD and EBS as PV for `LogSet`?
Yes
