### ISSUE TITLE
[Feature Request]: Umbrella issue of mo-runtime

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone-operator#143]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Per https://github.com/matrixorigin/matrixone-operator/blob/main/docs/rfc/2022-07-04-runtime.md, there are several features we are going to add at the framework level:

- [x] Framework skeleton, addressed in #125 
- [x] Utilities for k8s interaction
- [x] Object dependencies https://github.com/matrixorigin/matrixone-operator/pull/179
- [x] Out-of-box prometheus metrics https://github.com/matrixorigin/matrixone-operator/pull/266
- [ ] OpenTracing integration

**Comment by aylei** [comment]
Migrated to matrixorigin/controller-runtime
